#!/bin/bash

#TextColor
RED='\033[0;31m'
BLUE='\033[0;34m'
LINK='\033[0;94m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BAN='\033[0;92m'

NC='\033[0m' # No Color


mode="${1}"
domain="${2}"
urls="${3}"
DIR=`pwd`


function banner() {

	printf " ${BAN} 
███╗░░░███╗ ██████╗░ ░░░ ██████╗░ ███████╗ ░█████╗░ ░█████╗░ ███╗░░██╗
████╗░████║ ██╔══██╗ ░░░ ██╔══██╗ ██╔════╝ ██╔══██╗ ██╔══██╗ ████╗░██║
██╔████╔██║ ██████╔╝ ░░░ ██████╔╝ █████╗░░ ██║░░╚═╝ ██║░░██║ ██╔██╗██║
██║╚██╔╝██║ ██╔══██╗ ░░░ ██╔══██╗ ██╔══╝░░ ██║░░██╗ ██║░░██║ ██║╚████║
██║░╚═╝░██║ ██║░░██║ ██╗ ██║░░██║ ███████╗ ╚█████╔╝ ╚█████╔╝ ██║░╚███║
╚═╝░░░░░╚═╝ ╚═╝░░╚═╝ ╚═╝ ╚═╝░░╚═╝ ╚══════╝ ░╚════╝░ ░╚════╝░ ╚═╝░░╚══╝

			V0.0.2 (beta)
			Code By Tech Ghoshal with Love <3 ❤
	${NC}
	"
	printf "${RED}
Youtube:   https://www.youtube.com/@techghoshal
Twiter:    https://twitter.com/techghoshal
Facebook:  https://www.facebook.com/techghoshal

	${NC}"


}


	#Checking tool dependency
	function CheckingDependency() {

		banner
		echo -e ""
		sleep 1
		printf " ${BLUE}[+] Target: ${RED}${domain}\n${NC}"
		echo -e ""

		for tool in `cat dependency.txt`
		do

			if hash ${tool} 2>/dev/null; then
					
				printf " ${GREEN}[+] ${BLUE}${tool} found\n${NC}" 

			else
				printf " ${RED}[+] ${tool} could not be found\n${NC}"
				exit
			fi

		done

	}



# RECON 
function reconStart() {
		#Subfinder
		echo -e ""
		subfinder -d ${domain} -silent -t 100 -o ${domain}/recon/subfinderSubdomain.txt &


		#Ammass
		# Make sure to add Virustotal , Censys api Key
		sleep 1
		amass intel -whois -d ${domain} -o ${domain}/recon/amassIntelResults.txt &
		amass enum -passive -norecursive -noalts -config amass_config.ini -d ${domain} | tee ${domain}/recon/amassEnumResults.txt &


		#crt.sh
		sleep 1
		curl -s "https://crt.sh?q=${domain}&output=json" | jq ".[].common_name,.[].name_value" | cut -d'"' -f2 | sed 's/\\n/\n/g' | sed 's/\*.//g'| sed -r 's/([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})//g' | sort | uniq | tee ${domain}/recon/crtshResults.txt &

		#findomain
		findomain --target ${domain} --unique-output ${domain}/recon/findomain.txt & 


		#Subdomin Brute force use ffuf
		sleep 2
		ffuf -u "https://FUZZ.${domain}/" -w subdomains.txt -v | grep '| URL |' | grep -Po '.*?//\K.*?(?=/)' | tee ${domain}/recon/ffufBruteSubdResults.txt &


	   	#Sorting, httpx, waybackurl, dirsearch
	    sleep 1
	    
	    while [[ true ]]; do

	    	if [[ `ps -C amass | grep amass ` != *"amass"*  ]] && [[ `ps -C subfinder | grep subfinder ` != *"subfinder"*  ]] && [[ `ps -C ffuf | grep ffuf ` != *"ffuf"*  ]]
	    	then

	    		# amass sorting
				sort $DIR/${domain}/recon/amassEnumResults.txt $DIR/${domain}/recon/amassIntelResults.txt | uniq | tee ${domain}/recon/amassMainResults.txt

	    		#Subdomain Sorting
				sort $DIR/${domain}/recon/subfinderSubdomain.txt $DIR/${domain}/recon/amassMainResults.txt $DIR/${domain}/recon/crtshResults.txt $DIR/${domain}/recon/ffufBruteSubdResults.txt $DIR/${domain}/recon/findomain.txt | uniq | tee ${domain}/recon/allsub.txt 

				#httpx START
				cat ${domain}/recon/allsub.txt | httpx -threads 200 | tee -a ${domain}/recon/finalSubdomain.txt
				cat ${domain}/recon/allsub.txt | httpx -threads 200 -mc 200,301,302 -path /robots.txt -sc >> ${domain}/recon/robots.txt

				sleep 1
				#Waybackurl 
				waybackurls ${domain}/recon/finalSubdomain.txt | tee ${domain}/recon/waybackurls.txt

				#Collect JS file 
				cat  ${domain}/recon/waybackurls.txt | grep ".js$" | uniq | sort | tee -a ${domain}/recon/jsFile.txt

				sleep 1
				# SecretFinder
				cat ${domain}/recon/jsFile.txt | while read url; do python3 secretFinder/SecretFinder.py -i $url -o cli | tee -a ${domain}/recon/secret.txt; done


				#Ending Notify
				# echo -e "[ + ] Enumeration is Done." | notify -silent

				break

			fi

		done &
	}



#-------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------






if [ "$mode" == "" ] || [ "$mode" == "-h" ] || [ "$mode" == "--help" ] || [ "$mode" == "-help" ]
then

	banner
	echo -e ""
	printf " [HELP]\n${NC}"
	printf "   ${YELLOW}mrecon ${GREEN}-enum ${BLUE}target.com\n${NC}"

else
	
#--------------------------------------------------------------


#Checking tool dependency
CheckingDependency
sleep 1

##Enumeration START
	if [ "$mode" == "-enum" ] && [[ "$domain" == *"."* ]];
	then

		#Strating Notify 
		# echo -e ""
		# echo -e "[ + ] Enumeration START" | notify -silent
		# echo -e "[ + ] Target: ${domain}" | notify -silent
		# echo -e "[ + ] recon -enum ${domain}" | notify -silent


		mkdir ${domain}
		mkdir ${domain}/recon

		# recons function start
		reconStart #Subdomain Enumuration


	else
		echo -e ""
		printf " [HELP]\n${NC}"
		printf "   ${YELLOW}mrecon ${GREEN}-enum ${BLUE}target.com\n${NC}"
		echo -e ""
	fi

fi